services:
  postgres:
    image: postgres:16
    container_name: ticketing-postgres
    environment:
      POSTGRES_DB: ticketing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: ticketing-redis
    ports:
      - "6379:6379"